# Generated by Django 5.2.7 on 2025-10-20 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Set number (0-9,999,999).', validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('production_status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], help_text='Production status (ACTIVE/RETIRED).', max_length=16)),
                ('completeness', models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete')], help_text='Completeness (COMPLETE/INCOMPLETE).', max_length=16)),
                ('has_instructions', models.BooleanField(default=False)),
                ('has_box', models.BooleanField(default=False)),
                ('is_factory_sealed', models.BooleanField(default=False)),
                ('owner_initial_estimate', models.PositiveIntegerField(blank=True, help_text='Optional initial owner estimate in PLN (1-999,999).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricksets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brick Set',
                'verbose_name_plural': 'Brick Sets',
                'indexes': [models.Index(fields=['number'], name='brickset_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('number', 'production_status', 'completeness', 'has_instructions', 'has_box', 'is_factory_sealed'), name='brickset_global_identity'), models.CheckConstraint(condition=models.Q(('number__gte', 0), ('number__lte', 9999999)), name='brickset_number_range'), models.CheckConstraint(condition=models.Q(('owner_initial_estimate__isnull', True), models.Q(('owner_initial_estimate__gt', 0), ('owner_initial_estimate__lt', 1000000)), _connector='OR'), name='brickset_initial_estimate_range')],
            },
        ),
    ]
