# Generated by Django 5.2.7 on 2025-10-20 14:23

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brickset',
            managers=[
                ('bricksets', django.db.models.manager.Manager()),
            ],
        ),
    ]
