# Generated by Django 5.2.7 on 2025-10-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brickset_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brickset',
            managers=[
            ],
        ),
    ]
