# Generated by Django 5.2.7 on 2025-10-20 14:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('serviced_sets', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'valuation_metrics',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(help_text='Valuation value in PLN (1-999,999).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='Denormalized likes count >=0.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('brickset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='catalog.brickset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valuation',
                'verbose_name_plural': 'Valuations',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_likes', to=settings.AUTH_USER_MODEL)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='valuation.valuation')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['brickset'], name='valuation_brickset_idx'),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['user'], name='valuation_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.UniqueConstraint(fields=('user', 'brickset'), name='valuation_unique_user_brickset'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0), ('value__lt', 1000000)), name='valuation_value_range'),
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.CheckConstraint(condition=models.Q(('likes_count__gte', 0)), name='valuation_likes_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['valuation'], name='like_valuation_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='like_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'valuation'), name='like_unique_user_valuation'),
        ),
    ]
