# Generated by Django 5.2.7 on 2025-10-20 14:23

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brickset_managers'),
        ('valuation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='valuation',
            managers=[
                ('valuations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='valuation',
            name='valuation_value_range',
        ),
        migrations.AddConstraint(
            model_name='valuation',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0), ('value__lte', 999999)), name='valuation_value_range'),
        ),
    ]
